# Generated by Django 2.2 on 2021-05-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
